"""Regenerate skills/ampero2/reference.md from the package (CLI usage, protocol tables, catalog)."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ampero2 import cli, protocol as P  # noqa: E402
from ampero2.catalog import Catalog  # noqa: E402
from ampero2.patch import GLOBAL_EQ_FIELDS  # noqa: E402

OUT = ROOT / "skills" / "ampero2" / "reference.md"


def build() -> str:
    cat = Catalog.load()
    out = ["# ampero2 reference\n\nGenerated by `python3 tools/build_reference.py` from the package "
           "(CLI usage text, `protocol.py`, `patch.py`, `catalog.json`). Do not edit by hand.\n"]
    out.append("## Commands\n\n```\n" + cli.__doc__.strip() + "\n```\n")
    out.append("## Footswitch function codes (`footswitches`, `ctrl N fs`)\n\n| Function | Code |\n|---|---|")
    out += [f"| {k} | 0x{v:02X} |" for k, v in P.FOOTSWITCH_FUNCTIONS.items()]
    out.append("\nOther slot toggles, Bank+ and Patch- were not captured. In `ctrl N fs` the same list "
               "applies, but slot toggles A1.. start at 0x00 there.\n")
    out.append("## Global Settings ids (`global-set ID VALUE [PAGE]`)\n\n| Page | Id | Page byte | Field and values |\n|---|---|---|---|")
    out += [f"| {pg} | 0x{i:02X} | {b} | {name} |" for (pg, i), (b, name) in sorted(P.GLOBAL_PARAMS.items())]
    out.append("\nRead a page with `global PAGE` and check the byte after each write. Page 7 ids 1/2 are set "
               "with `ctrl`. No id is known for PATCH FS FUNC, the MIDI page, USB levels or display "
               "colour/brightness — do not guess: an unknown id or out-of-range value hangs the pedal.\n")
    out.append("## Global EQ fields (`eq-set BAND FIELD VALUE`)\n\n| Index | Band | Field |\n|---|---|---|")
    out += [f"| {i} | {b} | {f} |" for i, (b, f) in enumerate(GLOBAL_EQ_FIELDS)]
    out.append("\n`enabled` takes 0/1, `freq` Hz, `q` e.g. 0.71, `gain` dB.\n")
    out.append("## Catalog categories (`models CAT`, `model SLOT CAT \"Model\"`)\n\n| Index | Category | Models |\n|---|---|---|")
    out += [f"| {c.index} | {c.name} | {len(c.models)} |" for c in cat.categories]
    out.append("\nModel names are matched case-insensitively; quote names with spaces. `params CAT \"Model\"` "
               "prints the knob order — the knob INDEX for `param`, `quick-access` and `exp`.\n")
    out.append("## Numbers and layouts\n\n"
               "- Patch label `A<bank>-<pos>`, bank 1-60, pos 1-5; index = (bank-1)*5 + pos-1.\n"
               "- Slots 0-11 (line 1 = 0-5, line 2 = 6-11); a scene has one on/off bit per slot.\n"
               "- `show` prints knob values of scene 1; a `param` on scene 1 is copied to all 5 scenes, on scene 2-5 only that scene.\n"
               "- `save` stores the edit buffer into the given slot AND renames the buffer; `load` of the current patch is a no-op (load another patch first to re-read the flash).\n"
               "- Uploads: NAM `.nam` (JSON) and IR `.wav` are converted by the editor's `HTUSBTools.dylib`; CLONE `.clo` goes raw. Names: NAM/CLONE 16 chars, IR 31.\n"
               "- After a footswitch patch change the pedal broadcasts the new patch; `listen` prints it.\n")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    OUT.write_text(build())
    print(OUT)
